# Server configurations
server:
  debug: false
  # Listen on 0.0.0.0 rather than 127.0.0.1.
  # Listening on 127.0.0.1 (localhost) inside the container means it won't
  # accept connections from outside the container, including from your
  # host machine.
  host: "0.0.0.0"
  port: 4000
  write_timeout: 15
  read_timeout: 15
  ws_write_buffer_size: 1024
  ws_read_buffer_size: 1024
  ws_handshake_timeout: 180

# Game of life related config
game:
  fps: 12
  universe_prepend: true
  remove_static_universe_after: 30

# Logging related config
log:
  # Options: panic, fatal, error, warn, info, debug, trace
  level: info
  set_report_caller: false


